# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CMSC 141"
tagline: "Programming with Purpose"
description: University of Maryland, Fall 2023
author: David Van Horn
baseurl: '/cmsc141-www' # the subpath of your site, e.g. /blog
# url: 'https://www.cs.umd.edu' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

course_description: |+  
  This course is an introduction to computing and programming through
  the lens of data. It aims to give you ways of thinking about solving
  problems using computation. Students will learn to write programs to
  process both tabular and structured data, to assess programs both
  experimentally and theoretically, to apply basic data science
  concepts, and to discuss big ideas around the communication, use,
  and social impacts of digital information.
  
  The course is targeted to students with a broad diversity in
  backgrounds and interests. No prerequisites are assumed beyond high
  school algebra.

learning_objectives: |+
  1. Learn how to solve problems systematically using computational thinking.
  2. Write and debug programs using a high-level programming language.
  3. Understand the concept of algorithms and the importance of algorithm design in computer science.
  4. Learn to write programs to process both tabular and structured data.
  5. Apply statistical methods to analyze data and draw meaningful conclusions from it.
  6. Work with real-world data drawn from a diverse set of domains outside of computer science.
  7. Learn how to assess programs both experimentally and theoretically.
  8. Understand ethical considerations related to computing.
  9. Collect, clean, and manipulate data using common tools and programming languages.
  10. Learn how to specify and test behaviors of programs.

# FIXME: I don't know how to reference gradescope_url in aux_links below to avoid
# duplicating the URLs.

gradescope_url: "https://gradescope.com" # FIXME with actual course link

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.5.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Piazza:
    - '#'
  Gradescope:
    - '#'
  ELMS:
    - '#'

# Collections for website data
collections:
  homeworks:
    output: true
  projects:
    output: true
  staffers:
  modules:
  schedules:
  announcements:
  
# Default layouts for each collection type
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

callouts:
  highlight:
    title:
    color: yellow

# this is needed to enable search for collections
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    homeworks:
      name: Homeworks
      nav_exclude: true
      search_exclude: false

